name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage. Use flutter_secure_storage for the full flutter package.
repository: https://github.com/mogol/flutter_secure_storage
version: 1.1.3
publish_to: none


environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage_platform_interface:
    git:
      url: https://github.com/exilonX/flutter_secure_storage_roeid.git
      path: flutter_secure_storage_platform_interface

  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  lint: ^2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
